# Seata Server \u914D\u7F6E\uFF08TC - Transaction Coordinator\uFF09
# \u5B58\u50A8\u65B9\u5F0F\uFF1Adb/nacos/redis/file
store.mode=db
# \u6570\u636E\u5E93\u914D\u7F6E
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=utf8
store.db.user=root
store.db.password=root
store.db.minConn=5
store.db.maxConn=20
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000
# \u4E8B\u52A1\u5206\u7EC4
server.servicePort=8091
server.default.grouplist=127.0.0.1:8091
