# 应用配置（会被 Nacos 配置覆盖）
spring:
  profiles:
    active: dev

# Sentinel 配置
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
